name: spatial-transcriptomics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - scanpy
  - anndata
  - pandas
  - pyarrow
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - h5py
  - python-igraph
  - leidenalg
  - ipykernel
  - squidpy
