version: 2.1

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: pip install -e .[dev]
      - run:
          name: Run ruff
          command: ruff check src tests
      - run:
          name: Run mypy
          command: mypy src tests
      - run:
          name: Run pytest
          command: pytest
