version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: .
          pip-dependency-file: requirements-dev.txt

      - run:
          name: Install dev dependencies
          command: pip install -e .[dev]
      - run:
          name: Run ruff
          command: ruff check .
      - run:
          name: Run mypy
          command: mypy .
      - run:
          name: Run pytest
          command: pytest